export const LANGUAGE_MAP: Record<string, string> = {
    js: "JavaScript",
    ts: "TypeScript",
    jsx: "JSX",
    tsx: "TSX",
    html: "HTML",
    css: "CSS",
    scss: "SCSS",
    json: "JSON",
    py: "Python",
    python: "Python",
    rb: "Ruby",
    go: "Go",
    java: "Java",
    c: "C",
    cpp: "C++",
    cs: "C#",
    php: "PHP",
    sh: "Shell",
    bash: "Bash",
    sql: "SQL",
    yaml: "YAML",
    md: "Markdown",
    "": "Plain Text",
    plain: "Plain Text",
};
